### ISSUE TITLE
Test Issue1

### ISSUE THREAD

**Issue by thepoppe** [thepoppe/II1302-Project-Smart-Pet-Feeder#1]

**Comment by Lukassolna** [comment]
Do it yourself
________________________________
Från: Pontus Morin ***@***.***>
Skickat: den 9 april 2024 14:59
Till: thepoppe/II1302-Project-Smart-Pet-Feeder ***@***.***>
Kopia: Lukassolna ***@***.***>; Assign ***@***.***>
Ämne: Re: [thepoppe/II1302-Project-Smart-Pet-Feeder] Test Issue1 (Issue #1)


Assigned #1<https://github.com/thepoppe/II1302-Project-Smart-Pet-Feeder/issues/1> to @Lukassolna<https://github.com/Lukassolna>.
